name: 11
timestamp: 1629978636
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1517560458
positions:
  navigation-b: Navigation-b
  navigation-c: Navigation-c
  footer-a: Footer-a
  footer-b: Footer-b
  footer-c: Footer-c
  footer-d: Footer-d
  copyright-a: Copyright-a
sections:
  drawer: Drawer
  top: Top
  navigation: Navigation
  breadcrumb: Breadcrumb
  fullwidth: Fullwidth
  showcase: Showcase
  intro: Intro
  feature: Feature
  subfeature: Subfeature
  utility: Utility
  maintop: Maintop
  system-messages: System-messages
  sidebar: Sidebar
  mainbody: Mainbody
  mainbottom: Mainbottom
  extension: Extension
  additional: Additional
  prebottom: Prebottom
  bottom: Bottom
  afterbottom: Afterbottom
  last: Last
  copyright: Copyright
  to-top: To-top
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-6391: Logo
    logo-5307: 'Logo / Image'
    logo-9361: 'Logo / Image'
    logo-9148: 'Logo / Image'
    logo-4961: 'Logo / Image'
    logo-5390: 'Logo / Image'
    logo-5411: 'Logo / Image'
    logo-6527: 'Logo / Image'
  position:
    position-navigation-b: Navigation-b
    position-navigation-c: Navigation-c
    position-footer-a: Footer-a
    position-footer-b: Footer-b
    position-footer-c: Footer-c
    position-footer-d: Footer-d
    position-copyright-a: Copyright-a
  menu:
    menu-5268: Menu
  cta-button:
    cta-button-6614: 'CTA Button'
    cta-button-2740: 'CTA Button'
  content:
    system-content-9109: 'Page Content'
    system-content-9994: 'Page Content'
    system-content-9674: 'Page Content'
    system-content-5191: 'Page Content'
    system-content-5286: 'Page Content'
    system-content-1470: 'Page Content'
    system-content-8864: 'Page Content'
  spacer:
    spacer-6903: Spacer
  custom:
    custom-6709: 'Custom HTML'
    custom-1450: 'Custom HTML'
  hero-slider:
    hero-slider-1732: 'Hero Slider'
  page-title:
    page-title-8021: 'Page Title'
  gallery:
    gallery-1256: Gallery
    gallery-5045: Gallery
    gallery-5000: Gallery
    gallery-4327: Gallery
    gallery-8996: Gallery
inherit:
  default:
    drawer: drawer
    top: top
    header: header
    navigation: navigation
    breadcrumb: breadcrumb
    fullwidth: fullwidth
    showcase: showcase
    intro: intro
    feature: feature
    subfeature: subfeature
    utility: utility
    maintop: maintop
    system-messages: system-messages
    sidebar: sidebar
    mainbody: mainbody
    aside: aside
    mainbottom: mainbottom
    extension: extension
    additional: additional
    prebottom: prebottom
    bottom: bottom
    afterbottom: afterbottom
    last: last
    footer: footer
    copyright: copyright
    to-top: to-top
    offcanvas: offcanvas
    logo-6391: logo-6391
    position-navigation-b: position-navigation-b
    position-navigation-c: position-navigation-c
    menu-5268: menu-7495
    cta-button-6614: cta-button-3170
    cta-button-2740: cta-button-5138
    logo-5307: logo-4670
    system-content-9109: system-content-8217
    spacer-6903: spacer-6156
    custom-6709: custom-8950
    hero-slider-1732: hero-slider-1376
    page-title-8021: page-title-6487
    logo-9361: logo-8633
    logo-9148: logo-6634
    system-content-9994: system-content-5523
    system-content-9674: system-content-3958
    custom-1450: custom-7430
    logo-4961: logo-2579
    logo-5390: logo-3848
    system-content-5191: system-content-5235
    system-content-5286: system-content-9236
    logo-5411: logo-1610
    logo-6527: logo-9511
    system-content-1470: system-content-1470
    system-content-8864: system-content-6741
    gallery-1256: gallery-9169
    gallery-5045: gallery-4260
    gallery-5000: gallery-9212
    gallery-4327: gallery-6253
    gallery-8996: gallery-3907
    position-footer-a: position-footer-a
    position-footer-b: position-footer-b
    position-footer-c: position-footer-c
    position-footer-d: position-footer-d
    position-copyright-a: position-copyright-a
